[project]
name = "llm-model-filter"
version = "0.1.1"
readme = "README.md"
description = "Filter llm models list by starring favorites"
authors = [
    { name = "Thomas" },
]
license = {text = "Apache-2.0"}
classifiers = [
    "License :: OSI Approved :: Apache Software License"
]
dependencies = [
    "llm",
]

[project.urls]
Homepage = "https://github.com/irthomasthomas/llm-model-filter"
Changelog = "https://github.com/irthomasthomas/llm-model-filter/releases"
Issues = "https://github.com/irthomasthomas/llm-model-filter/issues"
CI = "https://github.com/irthomasthomas/llm-model-filter/actions"

[project.entry-points.llm]
model_filter = "llm_models_mod"

[project.optional-dependencies]
test = ["pytest"]
